### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by Leninsky** [christian-bromann/devtools-backend#2]
I tried node 8.6.0 with latest npm, there is something wrong with the webpack config.
Also I had to install gulp manually.

**Comment by christian-bromann** [comment]
What error message do you see?

**Comment by Leninsky** [comment]
https://github.com/isti37/devtools-backend/blob/builderror/builderror.log
https://github.com/isti37/devtools-backend/blob/builderror/2017-09-30T15_25_39_871Z-debug.log

Added node_modules and other stuff without .gitignore.

Also `git clone git@gitlab.fokus.fraunhofer.de:christian.bromann/devtools-backend.git `is not public, I cloned this with `https://github.com/christian-bromann/devtools-backend.git`

**Comment by christian-bromann** [comment]
This should be fixed now

**Comment by Zibri** [comment]
same here .. opened a new issue
