### ISSUE TITLE
Not able to see any calls in the inspector tool 

### ISSUE THREAD

**Issue by nehas510** [christian-bromann/devtools-backend#7]
<img width="1191" alt="screen shot 2018-03-11 at 3 53 47 pm" src="https://user-images.githubusercontent.com/20065178/37252962-93855bb0-2544-11e8-8a1c-f287f38023a9.png">
PFA the image of my chrome window. It connects but not able to see any calls

**Comment by christian-bromann** [comment]
> It connects but not able to see any calls

How do you see that it connected? This usually happens when the connection was not established.

**Comment by nehas510** [comment]
The server is running in the terminal.
<img width="724" alt="screen shot 2018-03-11 at 4 15 51 pm" src="https://user-images.githubusercontent.com/20065178/37253171-7f2b1dc8-2547-11e8-8341-f7719eaf90db.png">

**Comment by nehas510** [comment]
Also when I browse the Ip at that port I get this inspectable page. which means it is detecting my app.
<img width="1192" alt="screen shot 2018-03-11 at 4 16 39 pm" src="https://user-images.githubusercontent.com/20065178/37253178-ad93cb38-2547-11e8-8e20-074486095de3.png">

**Comment by christian-bromann** [comment]
Can you send the terminal logs once you have opened the devtools application?

**Comment by nehas510** [comment]
HI @christian-bromann,


1. I am able to connect the PI with the Wifi and then sharing the PI’s internet connection via the Ethernet to the TV.
2. I have injected this script in my Tizen app (.wgt) : <script src="http://10.10.30.190:9222/scripts/launcher.js" data-origin="debugger"></script> , where 10.10.30.190 is the IP address of the PI
3. Now I start the server from appium-hbbtv-driver using npm start command and as soon as I get Preflight check successful I launch my app and I get the following logs.
<img width="741" alt="screen shot 2018-03-12 at 10 03 32 am" src="https://user-images.githubusercontent.com/20065178/37267936-b4de95ae-25dc-11e8-9ac8-0a747fc20017.png">


<img width="724" alt="screen shot 2018-03-11 at 4 15 51 pm" src="https://user-images.githubusercontent.com/20065178/37266774-fd745ba2-25d5-11e8-9674-d3c3c5b8a6f5.png">

4. Now I try to open 10.10.30.190:9222 in Google chrome in my computer (which is on the same network)and I get this : 
<img width="1192" alt="screen shot 2018-03-11 at 4 16 39 pm" src="https://user-images.githubusercontent.com/20065178/37266784-120d7152-25d6-11e8-8067-51f3c52ad5c0.png">

5. When I click on this Starz-Tizen it opens an empty dev tool and I don’t get any logs :

<img width="1191" alt="screen shot 2018-03-11 at 3 53 47 pm" src="https://user-images.githubusercontent.com/20065178/37266798-22c4c5f4-25d6-11e8-937c-8037df685afa.png">


Do let me know if I am missing out something or if I am doing something wrong



Thanks,
Neha

**Comment by nehas510** [comment]
Can this be because the settings file is not available or corrupted? 
<img width="741" alt="screen shot 2018-03-12 at 10 03 32 am" src="https://user-images.githubusercontent.com/20065178/37271989-a75b71b0-25ee-11e8-995b-076a306df62d.png">

Do I need to modify anything in the settings file?

**Comment by christian-bromann** [comment]
@nehas510 that looks all good. Not sure why there is nothing to see. Can enter stuff in the console or do you see network events?

**Comment by nehas510** [comment]
NO network events or console logs as well :(

**Comment by christian-bromann** [comment]
mhm .. not really sure then

**Comment by nehas510** [comment]
oh....btw do I need to make any other changes in the app other than injecting the script?

I remember watching your webinar and there you mentioned something about adding the application/vnd.hbbtv..... in the Content-type?

I have my content type as : text/xml

**Comment by christian-bromann** [comment]
I looked into it and turns out that the devtools-frontend isn't compatible with the current Chrome version. Tried to update that package but having a hard time to configure it as the build process has changed.

**Comment by christian-bromann** [comment]
Ok, updated chrome-devtools-frontend and did a basic browser check and it seems to be working again. Please try and let me know.

**Comment by nehas510** [comment]
Hey @christian-bromann,
Looks like that did the trick!

 Thanks a lot. 
<img width="1040" alt="screen shot 2018-03-12 at 2 43 24 pm" src="https://user-images.githubusercontent.com/20065178/37279281-c106fda4-2603-11e8-9997-f709b89f76c2.png">

Now I am able to see the console logs however, I am still not getting the network calls.
<img width="1126" alt="screen shot 2018-03-12 at 2 40 13 pm" src="https://user-images.githubusercontent.com/20065178/37279254-ab6f6abc-2603-11e8-84c2-654602b72a68.png">

**Comment by christian-bromann** [comment]
> Looks like that did the trick!

Awesome 👍 

> I am still not getting the network calls.

This is probably because DevTools will only start listing it once you opened the tab. Try to go to that tab and reload the app or trigger some other network calls.

**Comment by nehas510** [comment]
This is probably because DevTools will only start listing it once you opened the tab. Try to go to that tab and reload the app or trigger some other network calls.

-- No I tried that I even tried to reload it couple of times but no luck

**Comment by christian-bromann** [comment]
Mhm..maybe because it can't detect the app as HbbTV app (https://github.com/christian-bromann/devtools-backend/blob/master/lib/proxy.js#L95). Your use case it probably different than mine so we might need some enhancements to get it working for your app.

**Comment by CHaNGeTe** [comment]
Same here! The update successfully made me see the console tab (and working).
But no luck with sources/network/elements

I managed to load the Elements tab by changing -as a quick hack-:
```
if (true/*payload && 'nodeId' in payload*/)
```
In DOMModel.js (from the fronted dependency)
It makes it load the Elements panel (with collapsible tree) but without CSS Properties, and all the actions from the Elements panel (add attribute / change html / etc)

But awesome work you did here!
I will love to have a WEINRE alternative and this project make me dream haha

I think @nehas510 and me are using it as a WEINRE alternative for smart tv projects (not hbbtv only) where debug options are quite limited.

Thanks for your work!

**Comment by nehas510** [comment]
Thanks @christian-bromann  and @CHaNGeTe  you are right. I am trying to use it as an alternative for weinre for smart TV project.  Do you guys have any idea/suggestions on how can I make it work for my app?

If you need more information about my app feel free to ask. Your help will be much appreciated.

Thanks a lot.
Neha
