### ISSUE TITLE
Frontend not loading

### ISSUE THREAD

**Issue by avaer** [christian-bromann/devtools-backend#8]
I can't get the frontend inspector to inspect a script-injected site. The inspector runtime throws this error when clicking through to inspect the target site in the inspect target list:

```
inspector.js:8213 Main._createAppUI: 19.367919921875ms
inspector.js:8213 Main._showAppUI: 6.758056640625ms
Uncaught TypeError: this._targetAgent.setAttachToFrames is not a function
    at new SDK.ChildTargetManager (inspector.js:3304)
    at SDK.TargetManager.createTarget (inspector.js:3277)
    at SDK.TargetManager._connectAndCreateMainTarget (inspector.js:3299)
    at SDK.TargetManager.connectToMainTarget (inspector.js:3296)
    at Main.Main._initializeTarget (inspector.js:8234)
```

The rest of the inspector loads, but nothing works, probably due to the above error.

<img width="959" alt="capture" src="https://user-images.githubusercontent.com/6926057/37253389-74ca4c54-2507-11e8-881e-61751502cb52.PNG">

Note that the target site (with injected script) _does_ seem to be correctly detected. It's just the user frontend attach that crashes.

**Comment by avaer** [comment]
I don't know if this is related, but the server console also gets stuck in an error spam loop:

```
ERR! devtools-backend:Proxy Internal request failed http://192.168.0.10:9222/scripts/socket.io.js.map Error: socket hang up
```

**Comment by avaer** [comment]
Might be same thing as https://github.com/christian-bromann/devtools-backend/issues/7

**Comment by avaer** [comment]
I managed to fix this by commenting out experimental lines in the upstream chrome-devtools-frontend.

But, I'm not sure if this is due to a problem locally or something upstream...

**Comment by christian-bromann** [comment]
Just pushed a fix for it.
